destination: ./_site
lsi:         false
port:        4000
highligher:  true
markdown:    rdiscount
permalink:   /:year/:month/:day/:title
email: "atmos@atmos.org"
url: "https://atmos.org"
exclude: [vendor]

rdiscount:
  extensions: [smart]
